# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/guoweijie004/workspaces/openSource-projects/ffmpeg-proj/fftoolsDebug

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/guoweijie004/workspaces/openSource-projects/ffmpeg-proj/fftoolsDebug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guoweijie004/workspaces/openSource-projects/ffmpeg-proj/fftoolsDebug/CMakeFiles /home/guoweijie004/workspaces/openSource-projects/ffmpeg-proj/fftoolsDebug//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guoweijie004/workspaces/openSource-projects/ffmpeg-proj/fftoolsDebug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ffprobe

# Build rule for target.
ffprobe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ffprobe
.PHONY : ffprobe

# fast build rule for target.
ffprobe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffprobe.dir/build.make CMakeFiles/ffprobe.dir/build
.PHONY : ffprobe/fast

#=============================================================================
# Target rules for targets named ffmpeg

# Build rule for target.
ffmpeg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ffmpeg
.PHONY : ffmpeg

# fast build rule for target.
ffmpeg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg.dir/build.make CMakeFiles/ffmpeg.dir/build
.PHONY : ffmpeg/fast

#=============================================================================
# Target rules for targets named ffmpeg_filter

# Build rule for target.
ffmpeg_filter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ffmpeg_filter
.PHONY : ffmpeg_filter

# fast build rule for target.
ffmpeg_filter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_filter.dir/build.make CMakeFiles/ffmpeg_filter.dir/build
.PHONY : ffmpeg_filter/fast

#=============================================================================
# Target rules for targets named ffplay

# Build rule for target.
ffplay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ffplay
.PHONY : ffplay

# fast build rule for target.
ffplay/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffplay.dir/build.make CMakeFiles/ffplay.dir/build
.PHONY : ffplay/fast

#=============================================================================
# Target rules for targets named ffmpeg_qsv

# Build rule for target.
ffmpeg_qsv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ffmpeg_qsv
.PHONY : ffmpeg_qsv

# fast build rule for target.
ffmpeg_qsv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_qsv.dir/build.make CMakeFiles/ffmpeg_qsv.dir/build
.PHONY : ffmpeg_qsv/fast

#=============================================================================
# Target rules for targets named ffmpeg_hw

# Build rule for target.
ffmpeg_hw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ffmpeg_hw
.PHONY : ffmpeg_hw

# fast build rule for target.
ffmpeg_hw/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_hw.dir/build.make CMakeFiles/ffmpeg_hw.dir/build
.PHONY : ffmpeg_hw/fast

#=============================================================================
# Target rules for targets named ffmpeg_opt

# Build rule for target.
ffmpeg_opt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ffmpeg_opt
.PHONY : ffmpeg_opt

# fast build rule for target.
ffmpeg_opt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_opt.dir/build.make CMakeFiles/ffmpeg_opt.dir/build
.PHONY : ffmpeg_opt/fast

#=============================================================================
# Target rules for targets named cmdutils

# Build rule for target.
cmdutils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cmdutils
.PHONY : cmdutils

# fast build rule for target.
cmdutils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdutils.dir/build.make CMakeFiles/cmdutils.dir/build
.PHONY : cmdutils/fast

cmdutils.o: cmdutils.c.o

.PHONY : cmdutils.o

# target to build an object file
cmdutils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdutils.dir/build.make CMakeFiles/cmdutils.dir/cmdutils.c.o
.PHONY : cmdutils.c.o

cmdutils.i: cmdutils.c.i

.PHONY : cmdutils.i

# target to preprocess a source file
cmdutils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdutils.dir/build.make CMakeFiles/cmdutils.dir/cmdutils.c.i
.PHONY : cmdutils.c.i

cmdutils.s: cmdutils.c.s

.PHONY : cmdutils.s

# target to generate assembly for a file
cmdutils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdutils.dir/build.make CMakeFiles/cmdutils.dir/cmdutils.c.s
.PHONY : cmdutils.c.s

ffmpeg.o: ffmpeg.c.o

.PHONY : ffmpeg.o

# target to build an object file
ffmpeg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg.dir/build.make CMakeFiles/ffmpeg.dir/ffmpeg.c.o
.PHONY : ffmpeg.c.o

ffmpeg.i: ffmpeg.c.i

.PHONY : ffmpeg.i

# target to preprocess a source file
ffmpeg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg.dir/build.make CMakeFiles/ffmpeg.dir/ffmpeg.c.i
.PHONY : ffmpeg.c.i

ffmpeg.s: ffmpeg.c.s

.PHONY : ffmpeg.s

# target to generate assembly for a file
ffmpeg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg.dir/build.make CMakeFiles/ffmpeg.dir/ffmpeg.c.s
.PHONY : ffmpeg.c.s

ffmpeg_filter.o: ffmpeg_filter.c.o

.PHONY : ffmpeg_filter.o

# target to build an object file
ffmpeg_filter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_filter.dir/build.make CMakeFiles/ffmpeg_filter.dir/ffmpeg_filter.c.o
.PHONY : ffmpeg_filter.c.o

ffmpeg_filter.i: ffmpeg_filter.c.i

.PHONY : ffmpeg_filter.i

# target to preprocess a source file
ffmpeg_filter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_filter.dir/build.make CMakeFiles/ffmpeg_filter.dir/ffmpeg_filter.c.i
.PHONY : ffmpeg_filter.c.i

ffmpeg_filter.s: ffmpeg_filter.c.s

.PHONY : ffmpeg_filter.s

# target to generate assembly for a file
ffmpeg_filter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_filter.dir/build.make CMakeFiles/ffmpeg_filter.dir/ffmpeg_filter.c.s
.PHONY : ffmpeg_filter.c.s

ffmpeg_hw.o: ffmpeg_hw.c.o

.PHONY : ffmpeg_hw.o

# target to build an object file
ffmpeg_hw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_hw.dir/build.make CMakeFiles/ffmpeg_hw.dir/ffmpeg_hw.c.o
.PHONY : ffmpeg_hw.c.o

ffmpeg_hw.i: ffmpeg_hw.c.i

.PHONY : ffmpeg_hw.i

# target to preprocess a source file
ffmpeg_hw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_hw.dir/build.make CMakeFiles/ffmpeg_hw.dir/ffmpeg_hw.c.i
.PHONY : ffmpeg_hw.c.i

ffmpeg_hw.s: ffmpeg_hw.c.s

.PHONY : ffmpeg_hw.s

# target to generate assembly for a file
ffmpeg_hw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_hw.dir/build.make CMakeFiles/ffmpeg_hw.dir/ffmpeg_hw.c.s
.PHONY : ffmpeg_hw.c.s

ffmpeg_opt.o: ffmpeg_opt.c.o

.PHONY : ffmpeg_opt.o

# target to build an object file
ffmpeg_opt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_opt.dir/build.make CMakeFiles/ffmpeg_opt.dir/ffmpeg_opt.c.o
.PHONY : ffmpeg_opt.c.o

ffmpeg_opt.i: ffmpeg_opt.c.i

.PHONY : ffmpeg_opt.i

# target to preprocess a source file
ffmpeg_opt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_opt.dir/build.make CMakeFiles/ffmpeg_opt.dir/ffmpeg_opt.c.i
.PHONY : ffmpeg_opt.c.i

ffmpeg_opt.s: ffmpeg_opt.c.s

.PHONY : ffmpeg_opt.s

# target to generate assembly for a file
ffmpeg_opt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_opt.dir/build.make CMakeFiles/ffmpeg_opt.dir/ffmpeg_opt.c.s
.PHONY : ffmpeg_opt.c.s

ffmpeg_qsv.o: ffmpeg_qsv.c.o

.PHONY : ffmpeg_qsv.o

# target to build an object file
ffmpeg_qsv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_qsv.dir/build.make CMakeFiles/ffmpeg_qsv.dir/ffmpeg_qsv.c.o
.PHONY : ffmpeg_qsv.c.o

ffmpeg_qsv.i: ffmpeg_qsv.c.i

.PHONY : ffmpeg_qsv.i

# target to preprocess a source file
ffmpeg_qsv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_qsv.dir/build.make CMakeFiles/ffmpeg_qsv.dir/ffmpeg_qsv.c.i
.PHONY : ffmpeg_qsv.c.i

ffmpeg_qsv.s: ffmpeg_qsv.c.s

.PHONY : ffmpeg_qsv.s

# target to generate assembly for a file
ffmpeg_qsv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeg_qsv.dir/build.make CMakeFiles/ffmpeg_qsv.dir/ffmpeg_qsv.c.s
.PHONY : ffmpeg_qsv.c.s

ffplay.o: ffplay.c.o

.PHONY : ffplay.o

# target to build an object file
ffplay.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffplay.dir/build.make CMakeFiles/ffplay.dir/ffplay.c.o
.PHONY : ffplay.c.o

ffplay.i: ffplay.c.i

.PHONY : ffplay.i

# target to preprocess a source file
ffplay.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffplay.dir/build.make CMakeFiles/ffplay.dir/ffplay.c.i
.PHONY : ffplay.c.i

ffplay.s: ffplay.c.s

.PHONY : ffplay.s

# target to generate assembly for a file
ffplay.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffplay.dir/build.make CMakeFiles/ffplay.dir/ffplay.c.s
.PHONY : ffplay.c.s

ffprobe.o: ffprobe.c.o

.PHONY : ffprobe.o

# target to build an object file
ffprobe.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffprobe.dir/build.make CMakeFiles/ffprobe.dir/ffprobe.c.o
.PHONY : ffprobe.c.o

ffprobe.i: ffprobe.c.i

.PHONY : ffprobe.i

# target to preprocess a source file
ffprobe.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffprobe.dir/build.make CMakeFiles/ffprobe.dir/ffprobe.c.i
.PHONY : ffprobe.c.i

ffprobe.s: ffprobe.c.s

.PHONY : ffprobe.s

# target to generate assembly for a file
ffprobe.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffprobe.dir/build.make CMakeFiles/ffprobe.dir/ffprobe.c.s
.PHONY : ffprobe.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cmdutils"
	@echo "... ffmpeg"
	@echo "... ffmpeg_filter"
	@echo "... ffmpeg_hw"
	@echo "... ffmpeg_opt"
	@echo "... ffmpeg_qsv"
	@echo "... ffplay"
	@echo "... ffprobe"
	@echo "... cmdutils.o"
	@echo "... cmdutils.i"
	@echo "... cmdutils.s"
	@echo "... ffmpeg.o"
	@echo "... ffmpeg.i"
	@echo "... ffmpeg.s"
	@echo "... ffmpeg_filter.o"
	@echo "... ffmpeg_filter.i"
	@echo "... ffmpeg_filter.s"
	@echo "... ffmpeg_hw.o"
	@echo "... ffmpeg_hw.i"
	@echo "... ffmpeg_hw.s"
	@echo "... ffmpeg_opt.o"
	@echo "... ffmpeg_opt.i"
	@echo "... ffmpeg_opt.s"
	@echo "... ffmpeg_qsv.o"
	@echo "... ffmpeg_qsv.i"
	@echo "... ffmpeg_qsv.s"
	@echo "... ffplay.o"
	@echo "... ffplay.i"
	@echo "... ffplay.s"
	@echo "... ffprobe.o"
	@echo "... ffprobe.i"
	@echo "... ffprobe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

